In [3]:
import numpy as np

In [333]:
#Test Cases
A1 = [[1,2],[2,3]]
B1 = [[6,5],[9,9]]
a1 = np.array(A1)
b1 = np.array(B1)

A2 = [[1,2,0,1],[2,3,7,8],[6,2,4,6], [7,1,7,4]]
B2 = [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,31,4]]
a2 = np.array(A2)
b2 = np.array(B2)

A3 = np.random.randint(5, size=(8,8))
B3 = np.random.randint(5, size =(8,8))
a3 = np.array(A3)
b3 = np.array(B3)

In [334]:
def matrix_mul(A, B):
    n = len(A)
    if n <= 2:
        C = [[0]*n for m in range(n) ] 
        for i in range(n):
            for j in range(n):
                sum = 0 
                for k in range(n):
                    sum += A[i][k] * B[k][j]
                    if k == (n-1): #When k finishes loop through n 
                        C[i][j] = sum #put the sum of A*B matrix in C
        return C
    else: 
        mid = n//2  

        A11 = A[0:mid,0:mid]
        A12 = A[0:mid,mid:]
        A21 = A[mid:,0:mid]
        A22 = A[mid:,mid:]
        B11 = B[0:mid,0:mid]
        B12 = B[0:mid,mid:]
        B21 = B[mid:,0:mid]
        B22 = B[mid:,mid:]
        
        C11 = np.add(matrix_mul(A11,B11),matrix_mul(A12, B21))
        C12 = np.add(matrix_mul(A11,B12), matrix_mul(A12, B22))
        C21 = np.add(matrix_mul(A21,B11), matrix_mul(A22, B21))
        C22 = np.add(matrix_mul(A21,B12), matrix_mul(A22, B22))
        C = np.bmat([[C11, C12], [C21, C22]])
#         C = [C11,C12,C21,C22]
        return C
        

In [335]:
print(a1.dot(b1))
print()
print(matrix_mul(a1,b1))

[[24 23]
 [39 37]]

[[24, 23], [39, 37]]


In [336]:
matrix_mul(a2,b2)
print()
print(a2.dot(b2))


[[  9   9  36   9]
 [ 61  61 277  61]
 [ 46  46 208  46]
 [ 46  46 154  46]]


In [337]:
print(matrix_mul(a3,b3))
print()
print(a3.dot(b3))

[[45 37 43 28 54 57 51 45]
 [31 12 22 22 31 30 34 24]
 [13 26 18  8 18 23 14 16]
 [26 26 23 15 33 36 26 25]
 [46 41 41 38 60 62 45 46]
 [36 21 36 26 40 44 40 32]
 [49 37 48 39 43 49 41 47]
 [16 21 22 14 22 28 10 19]]

[[45 37 43 28 54 57 51 45]
 [31 12 22 22 31 30 34 24]
 [13 26 18  8 18 23 14 16]
 [26 26 23 15 33 36 26 25]
 [46 41 41 38 60 62 45 46]
 [36 21 36 26 40 44 40 32]
 [49 37 48 39 43 49 41 47]
 [16 21 22 14 22 28 10 19]]


## Problem
1. List of lists changes reflected across sublists unexpectedly: https://stackoverflow.com/questions/240178/list-of-lists-changes-reflected-across-sublists-unexpectedly